[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run db:push --force && node scripts/migrate.js && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300

[nixpacks]
nixPkgs = ["nodejs_20"]
